POST http://localhost:3000/api/users
Content-Type: application/vnd.api+json

{
    "firstName": "Test2",
    "lastName": "Testovich2",
    "email": "test2@test.test",
    "passwordHash": "admin",
    "birthday": "2000-12-13 11:11",
    "gender": "male"
}